### PR TITLE
Combined SSD1351 Examples

### PR DESCRIPTION
**Pull request by makermelissa**
This should compile for the ESP8266 now.

### CODE REVIEW

**Comment by ladyada** [comment]
this is weird, hardware SPI exists on the ESP8266 - let me look

**Comment by ladyada** [comment]
oh ok for ESP8266 please try
`Adafruit_SSD1351 tft = Adafruit_SSD1351(SCREEN_WIDTH, SCREEN_HEIGHT, TFT_CS, TFT_DC,  TFT_RST);`
don't define SCK/MOSI, it will have problems with sharing those pins

**Comment by makermelissa** [comment]
Ok thanks, I’ll try that

**Comment by makermelissa** [comment]
I have verified this works on the Teensy 3.6 and ESP8266 with the SSD1351. Also this includes the refactor of the SSD1351 bmp example to use this library.

**Comment by ladyada** [comment]
ok i think you can remove the #ifdef ESP8266s now right? it works with hardware SPI :)

**Comment by makermelissa** [comment]
Oh, yeah. I just tested and it's working great without the conditionals.

**Comment by ladyada** [comment]
change name from BreakoutSSD1351-128x128.ino to BreakoutSSD1351.ino

**Comment by makermelissa** [comment]
The guide at https://learn.adafruit.com/adafruit-1-5-color-oled-breakout-board has been updated.

**Pull request merged**
